#!/bin/bash

# Tom Lee <thomlee@indiana.edu>
# begun on 2008/04/02
# last modified 2012/12/21

# This file will be synchronized using puppet across all servers and should
# therefore contain only rules that should apply to all GOC servers.

# This file should not set any policies or define any chains.  It should
# contain the rules that will apply across the board to all GOC servers.  For
# more information, see /etc/iptables.d/README.

###############################################################################
# Preparation
###############################################################################

. /etc/iptables.d/setup

###############################################################################
# Basic rules
###############################################################################

# Allow broadcast packets
$ITFAI -j cast_ok

# Let jump/jump2 always connect via ssh as a special case
$ITFAI -p tcp --dport ssh -j jump_ok

# Handle packets destined for private VLAN addresses.
$ITFAI -j handle_priv

# Drop packets from blacklisted hosts.
$ITFAI -j global_blacklist

# Debug: Log any other incoming packets
#$ITFAI -j log_accept

# Run a few chains that should be in effect for all servers

# Always allow ICMP
$ITFAI -j icmp_ok

# Always allow Nagios from GRNOC to ssh
$ITFAI -j grnoc_ok

# Allow all packets from UISO ranges for security scanning
$ITFAI -j uiso_ok

# Let known hosts connect via ssh
$ITFAI -p tcp --dport ssh -j known_ok

# Add dynamic DNS hosts, if network is up and if the script exists
if /sbin/ip link show eth0 | /bin/grep -Fq UP; then
    if [ -x /opt/sbin/confsync-dyndns ]; then
	/opt/sbin/confsync-dyndns
    fi
fi
