#!/bin/bash

# Tom Lee <thomlee@indiana.edu>
# begun 2008/04/04
# last modified 2013/10/03

# This file contains rules that should apply to all GOC servers.  It will be
# synchronized with them via puppet.

# This script merely adds rules to reject any packets that have not yet been
# accepted or already dropped or rejected for other reasons.  It should contain
# no other rules.  For more information, see /etc/iptables.d/README.

###############################################################################
# Preparation
###############################################################################

. /etc/iptables.d/setup

###############################################################################
# Precaution
###############################################################################

if [[ `iptables -n -t filter -L INPUT | wc -l` -lt 3 ]]; then
    # If the only two lines in the output of that iptables -L command above are
    # the header lines, something's gone seriously wrong with the other scripts
    # in this sequence.  If that's the case, let's leave some breathing room so
    # we don't lose contact with the server completely. -- TJL 2012/10/04

    echo "WARNING! Iptables filter/INPUT rule is empty! Entering failsafe mode." > /dev/stderr
    $ITF -P INPUT ACCEPT
    $ITF -P OUTPUT ACCEPT
    $ITF -P FORWARD ACCEPT
fi

###############################################################################
# Dropping packets
###############################################################################

# Log and reject any incoming packets that haven't been accepted by some rule
# yet.  Technically, this is not necessary for security, since the filter
# table's INPUT chain has a policy of REJECT already (see 20-global-policies),
# but if we want them logged, we have to do this.
$ITFAI -j log_reject
