#!/bin/bash

# Tom Lee <thomlee@indiana.edu>
# begun on 2012/10/04
# last modified 2014/04/30

# This file will be synchronized using puppet across all servers and should
# therefore contain only rules that should apply to all GOC servers.

# This file only exists to set up iptables to be compatible with
# packet-counting system monitors.

###############################################################################
# Preparation
###############################################################################

. /etc/iptables.d/setup

###############################################################################
# Rules
###############################################################################

# Rules that don't really do anything but notice packets so that packet-count
# monitors (like Munin's) can monitor network traffic

if [[ $IP6_VLAN259 ]]; then
    $ITFAI -d $IP6_VLAN259/128
    $ITFAO -s $IP6_VLAN259/128
fi

if [[ $IP4_VLAN259 ]]; then
    $ITFAI4 -d $IP4_VLAN259/32
    $ITFAO4 -s $IP4_VLAN259/32
fi

if [[ $IP6_VLAN4020 ]]; then
    $ITFAI -d $IP6_VLAN4020/128
    $ITFAO -s $IP6_VLAN4020/128
fi

if [[ $IP4_VLAN4020 ]]; then
    $ITFAI4 -d $IP4_VLAN4020/32
    $ITFAO4 -s $IP4_VLAN4020/32
fi
