#!/bin/bash
echo "RHN Satellite Client bootstrap script v1.0"
echo "-----------------------------------------------------"

# This file was autogenerated. Minor manual editing of this script (and
# possibly the client-config-overrides.txt file) is necessary to complete the
# bootstrap setup. Editing of this script is described later. Once customized,
# the bootstrap script can be triggered in one of two ways:
#   (1) centrally, from the RHN Satellite via ssh, or
#   (2) in a decentalized manner on each client via wget. Method #1 is
#       preferred.
#
# Usage examples:
# o after editing, centrally managed client setup; i.e., from the
#   RHN Satellite:
#     cd /var/www/html/pub/bootstrap/
#     cat bootstrap-<edited_name>.sh | ssh root@<client-hostname> /bin/bash
#
#   ...or...
#
# o after editing, decentrallized client setup; i.e., executed from the client
#   itself:
#     wget -q -O - https://<sat-hostname>/pub/bootstrap/bootstrap-<edited_name>.sh | /bin/bash
#

# SECURITY NOTE:
#   Use of these scripts via the two methods discussed is the most expedient
#   way to register machines to your RHN Satellite. Throughout the
#   script, wget is run to download various files. "Man-in-the-middle" attacks
#   are possible!
#
#   The actual registration is performed securely via SSL, so the risk is
#   minimized in a sense. This message merely serves as a warning. Most
#   customers will not be concerned since they are operating within their own
#   organization.
#
# PROVISIONING/KICKSTART NOTE:
#   A client, in order to be properly provisioned with operational SSL needs to
#   have the SSL CA Cert installed. In order to do this, the package,
#   rhn-org-trusted-ssl-cert-<version>-<release).noarch.rpm, will need to be
#   imported into a child channel of the pertinent base operating system
#   channel. This child channel needs to also be accessible to the client.
# 

# set wget_args based on version
wget_version=`wget -V | head -n1 | awk '{ print $3 }' | cut -d. -f2`

if [ $wget_version -ge 10 ]
then
wget_args="-q -N --no-check-certificate"
else
wget_args="-q -N"
fi

# edit these:
ACTIVATION_KEY=server
ORG_GPG_KEY=insert_org-pub-key.gpg_here_unless_not_using
USING_ORG_GPG_KEY=0

# can be edited, but probably correct:
CLIENT_OVERRIDES=client-config-overrides.txt
HOSTNAME=rhn.ussg.indiana.edu
ORG_CA_CERT_RPM=rhn-org-trusted-ssl-cert-1.0-1.noarch.rpm

#
# -----------------------------------------------------------------------------
# DO NOT EDIT BEYOND THIS POINT -----------------------------------------------
# -----------------------------------------------------------------------------
#

HTTP_PUB_DIRECTORY=http://${HOSTNAME}/pub
HTTPS_PUB_DIRECTORY=https://${HOSTNAME}/pub
echo
echo "UPDATING RHN_REGISTER/UP2DATE CONFIGURATION FILES"
echo "-------------------------------------------------"
echo "* downloading necessary files"
echo "  client_config_update.py..."
wget $wget_args ${HTTPS_PUB_DIRECTORY}/bootstrap/client_config_update.py
echo "  ${CLIENT_OVERRIDES}..."
wget $wget_args ${HTTPS_PUB_DIRECTORY}/bootstrap/${CLIENT_OVERRIDES}

if [ ! -f "client_config_update.py" ] ; then
    echo "ERROR: client_config_update.py was not downloaded"
    exit 1
fi
if [ ! -f "${CLIENT_OVERRIDES}" ] ; then
    echo "ERROR: ${CLIENT_OVERRIDES} was not downloaded"
    exit 1
fi

echo "* running the update scripts"
if [ -f "/etc/sysconfig/rhn/rhn_register" ] ; then
    echo "  . rhn_register config file"
    /usr/bin/python -u client_config_update.py /etc/sysconfig/rhn/rhn_register ${CLIENT_OVERRIDES}
fi
echo "  . up2date config file"
/usr/bin/python -u client_config_update.py /etc/sysconfig/rhn/up2date ${CLIENT_OVERRIDES}

if [ $USING_ORG_GPG_KEY -eq 1 ] ; then
    echo
    echo "IMPORTING GPG KEYS"
    echo "------------------"
    echo "* importing gpg key"
    wget $wget_args ${HTTPS_PUB_DIRECTORY}/${ORG_GPG_KEY}
    rpm --import $ORG_GPG_KEY
fi

echo
echo "INSTALLING CORPORATE PUBLIC CA CERT"
echo "-----------------------------------"
echo "* attempting to install corporate public CA cert"
echo "  need to do in a seperate step for the time being"
rpm -Uvh ${HTTP_PUB_DIRECTORY}/${ORG_CA_CERT_RPM}

echo
echo "REGISTRATION"
echo "------------"
# Should have created an activation key on the RHN Satellite's
# website and edited the value of ACTIVATION_KEY above.
#
# If you require use of several different activation keys, copy this file and
# change the string as needed.
#
echo "* registering"
rhnreg_ks --force --activationkey $ACTIVATION_KEY
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
echo
echo "*** this system should now be registered, please verify"
echo
echo "-bootstrap complete-"
echo "Please run \"yum update\" to setup yum for updates."
